name: Deploy Ondergrond

on:
  push:
    branches:
      - main      # Deploy to staging
      - develop   # Deploy to dev
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test:coverage

      - name: Build application
        run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install CDK dependencies
        run: |
          cd infrastructure
          npm ci

      - name: Determine environment
        id: env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "stack_name=Ondergrond-Infrastructure-Staging" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "stack_name=Ondergrond-Infrastructure-Dev" >> $GITHUB_OUTPUT
          fi

      - name: Deploy infrastructure
        run: |
          cd infrastructure
          npx cdk deploy ${{ steps.env.outputs.stack_name }} --require-approval never

      - name: Output deployment URL
        run: |
          cd infrastructure
          aws cloudformation describe-stacks --stack-name ${{ steps.env.outputs.stack_name }} --query 'Stacks[0].Outputs'